apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: eccfe
build:
  artifacts:
    - image: eccfe
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
deploy:
  kustomize:
    paths:
      - k8s
