apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: eccfe
build:
  artifacts:
    - image: eccfe
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
manifests:
  kustomize:
    paths:
      - k8s
deploy:
  kubectl: {}
